name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: |
      node testApp.mjs &&
      node testCategories.mjs &&
      node testDatasafety.mjs &&
      node testDeveloper.mjs &&
      node testList.mjs &&
      node testPermissions.mjs &&
      node testReviews.mjs &&
      node testSearch.mjs &&
      node testSimilar.mjs &&
      node testSuggest.mjs


